apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-microservice
  template:
    metadata:
      labels:
        app: todo-microservice
    spec:
      containers:
      - name: todo-microservice
        image: serkanalgl/todo-microservice:latest
        ports:
        - containerPort: 8000