apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
      - name: user-microservice
        image: serkanalgl/user-microservice:latest
        ports:
        - containerPort: 8000